name: Deploy to VPS

on:
  push:
    branches:
      - dev  # Adjust if your default branch is named differently

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        env:
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_IP: ${{ vars.VPS_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$VPS_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        env:
          VPS_USER: ${{ vars.VPS_USER }}
          VPS_IP: ${{ vars.VPS_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP "docker ps"

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP << 'EOF'
          cd /home/root/frontend
          git pull origin dev
          docker build -t angular-app .
          EOF

